import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import Header from "../components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ReNex Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Real Estate Page</title>
        <link
          href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
          rel="stylesheet"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"
          defer // Ensures the script runs after the HTML is parsed
        ></script>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 flex flex-col lg:flex-row justify-around w-full`}
      >
        <div className="bg-gray-300 rounded-lg border border-gray-400 m-2 lg:h-48 lg:w-1/5 lg:mt-72 invisible lg:visible h-0 w-0 lg:sticky lg:top-48"></div>
          <Header />
        <div className="w-full lg:w-1/2">
          {/* <Header /> */}
          {children}
        </div>
          <Footer />
        <div className="bg-gray-300 rounded-lg border border-gray-400 m-2 lg:h-48 lg:w-1/5 lg:mt-56 invisible lg:visible h-0 w-0 lg:sticky lg:top-48"></div>
      </body>
    </html>
  );
}
